name: Build bi_exporter test image and run tests on it
run-name: Build bi_exporter test image and run tests on it - started by ${{ github.actor }}
on:
  pull_request:
    types: [opened, synchronize]
    paths:
    - 'bi_exporter/**'
  workflow_dispatch:


jobs:
  build_image:
    runs-on: self-hosted
    steps:
      - name: Check out actions code
        uses: actions/checkout@v3
      - name: Login to Docker Hub (optional)
        env:
          username: ${{ secrets.EXT_DOCKER_LOGIN }}
          password: ${{ secrets.EXT_DOCKER_TOKEN }}
        if: ${{ env.username != '' && env.password != ''}}
        uses: docker/login-action@v3
        with:
          username: ${{ env.username }}
          password: ${{ env.password }}
      - name: Build image
        run: bash -x build.sh bi_exporter build
      - name: Build test image and run tests
        run: bash -x bi_exporter/run_test.sh
