name: Build bulldozer test image and run tests on it
run-name: Build bulldozer test image and run tests on it - started by ${{ github.actor }}
on:
  pull_request:
    types: [opened, synchronize]
    paths:
    - 'bulldozer/**'
  workflow_dispatch:


jobs:
  build_image:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.EXT_DOCKER_LOGIN }}
          password: ${{ secrets.EXT_DOCKER_TOKEN }}
      - name: Build image
        run: bash -x build.sh bulldozer build
      - name: Build test image and run tests
        run: bash -x bulldozer/run_test.sh
